@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-down-> "1" UniqueStallList
AddressBook *-right-> "1" UniqueReviewList

UniqueReviewList *-right-> "*" Review
UniqueStallList -right-> Stall

Stall -up-> "*" Review

Stall *--> Address
Stall *--> Name
Stall *--> Tag

Address -[hidden]right- Name
Stall -[hidden]right- Tag

Review *-right-> Date
Review *-right-> Content
Review *-right-> Rating
Review *--> Name
Review *--> Tag

Date -[hidden]down- Content
Date -[hidden]down- Rating
@enduml
