@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":SDeleteCommandParser" as SDeleteCommandParser LOGIC_COLOR
participant "d:SDeleteCommand" as SDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant "storage:Storage" as Storage STORAGE_COLOR
end box

[-> LogicManager : execute("sdel 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sdel 1")
activate AddressBookParser

create SDeleteCommandParser
AddressBookParser -> SDeleteCommandParser
activate SDeleteCommandParser

SDeleteCommandParser --> AddressBookParser
deactivate SDeleteCommandParser

AddressBookParser -> SDeleteCommandParser : parse("1")
activate SDeleteCommandParser

create SDeleteCommand
SDeleteCommandParser -> SDeleteCommand
activate SDeleteCommand

SDeleteCommand --> SDeleteCommandParser : d
deactivate SDeleteCommand

SDeleteCommandParser --> AddressBookParser : d
deactivate SDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SDeleteCommandParser -[hidden]-> AddressBookParser
destroy SDeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> SDeleteCommand : execute(model)
activate SDeleteCommand

SDeleteCommand -> Model : getFilteredStallList()
activate Model

Model -> SDeleteCommand
deactivate Model

SDeleteCommand -> Model : deleteStall(stall)
activate Model

Model --> SDeleteCommand
deactivate Model

create CommandResult
SDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> SDeleteCommand
deactivate CommandResult

SDeleteCommand -> Model : getAddressBook
activate Model

Model --> SDeleteCommand : addressBook
deactivate Model

SDeleteCommand -> Storage : saveAddressBook(addressBook)
activate Storage

Storage --> SDeleteCommand
deactivate Storage

SDeleteCommand --> LogicManager : result
deactivate SDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
